apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: kn08
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
			app: account
		spec:
			containers:
				- name: account
					image: sxnic/kn08-account:latest
					ports:
						- containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
	name: account-service
	namespace: kn08
spec:
	type: ClusterIP
	selector:
		app: account
	ports:
		- protocol: TCP
			port: 80
			targetPort: 8080