apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: kn08
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: sxnic/kn08-frontend:v1
                  ports:
                      - containerPort: 3000
                  env:
                    - name: REACT_APP_ACCOUNT_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: account-config
                          key: account-host
                    - name: REACT_APP_ACCOUNT_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: account-config
                          key: account-port
                    - name: REACT_APP_BUYSELL_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: buysell-config
                          key: buysell-host
                    - name: REACT_APP_BUYSELL_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: buysell-config
                          key: buysell-port
                    - name: REACT_APP_SENDRECEIVE_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: sendreceive-config
                          key: sendreceive-host
                    - name: REACT_APP_SENDRECEIVE_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: sendreceive-config
                          key: sendreceive-port
                    - name: REACT_APP_USER_LOGGED_IN
                      valueFrom:
                        configMapKeyRef:
                          name: frontend-config
                          key: logged-in-user-id
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: kn08
spec:
    type: NodePort
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30080