apiVersion: apps/v1
kind: Deployment
metadata:
    name: sendreceive-deployment
    namespace: kn08
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sendreceive
    template:
        metadata:
            labels:
                app: sendreceive
        spec:
            containers:
                - name: sendreceive
                  image: sxnic/kn08-sendreceive:v2
                  ports:
                    - containerPort: 8003
                  env:
                      - name: PORT
                        valueFrom:
                            configMapKeyRef:
                                name: sendreceive-config
                                key: sendreceive-port
                      - name: ACCOUNT_SERVICE_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: account-config
                                key: account-host
                      - name: ACCOUNT_SERVICE_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: account-config
                                key: account-port
---
apiVersion: v1
kind: Service
metadata:
    name: sendreceive-service
    namespace: kn08
spec:
    selector:
        app: sendreceive
    ports:
        - protocol: TCP
          port: 8003
          targetPort: 8003