apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: kn08
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: sxnic/kn08-frontend:v1
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                          name: frontend-env
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: kn08
spec:
    type: NodePort
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30080