apiVersion: apps/v1
kind: Deployment
metadata:
    name: buysell-deployment
    namespace: kn08
    labels:
        app: buysell
spec:
    replicas: 1
    selector:
        matchLabels:
            app: buysell
    template:
        metadata:
            labels:
                app: buysell
        spec:
            containers:
                - name: buysell
                  image: sxnic/kn08-buysell:v2
                  ports:
                      - containerPort: 8002
                  env:
                      - name: PORT
                        valueFrom:
                            configMapRef:
                                name: buysell-env
                                key: port
                      - name: ACCOUNT_SERVICE_URL
                        valueFrom:
                            configMapRef:
                                name: account-env
                                key: url
---
apiVersion: v1
kind: Service
metadata:
    name: buysell-service
    namespace: kn08
spec:
    selector:
        app: buysell
    ports:
        - protocol: TCP
          port: 8002
          targetPort: 8002