#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpP/VqcY7n2W2qOQHbWXQ27GfyXUKlMyccvPhXduw74fwPTH6Mjh5jrCm0HMebBqS79N/4EcewMJPfOxbkUDX54NJ5+pT4E3bs8LPYa1uq1ipOOLUnP5l0ogf4xVqYp9zU7YNoGW5bIaLn39I5/aLZtedqrGyBc52IQQ/UADbn9cGCnHx43KJPocHRfvMpFYn46hzOLqxIqVKEqMfn1NaWPqIXyZVGN7goxRN7aovqn5ihNKRyx7waNXdmIcbrBv3A1b2Ziwyq8BPveWnywyt788OJBtX38Z9esW5gis3PtGyD2Bj49ITu+JIVJbDQ3wVW/ah3o63thfSuhISQTTh4AOIygqTl5TD3Q6YWcMwN7enMc5Q2ToMzxXbIlO1lAujHRkZXgaRd8pMFHshwEjjd9ODff8vVQV8pkgWZj7lIPK407UCm1uC4ogO7BOLaCiCYzmb7x/SwM60P1OUQdIIxNGpauRQ4HJ7VeeHWcQ8DqUjG0WxiN64x++0+HkLoVuKQVw8zzPlV6G8ULPaM79JWf/SKR1pqnYHOVe/Lw/BTBYDjwwG231TYshB3N93sYFTInzC5ai6hlrUOEVQs4v5AqCCtDc3dIcbtB2d1WLTIPSQ0CnX5X5S9oLlh2t7QSkcahNr7Fv8MOS47Vj4xfjJ1bfCC27LEkqLupqoRV0JCmQ== sxnic@sxnic
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [docker]
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
final_message: "The system is finally up, after $UPTIME seconds"
write_files:
  - path: /home/ubuntu/.docker/web.Dockerfile
    permissions: '0644'
    content: |
      FROM php:8.3.20-apache
      WORKDIR /var/www/html
      RUN docker-php-ext-install mysqli
      COPY ./php .
      EXPOSE 80
  - path: /home/ubuntu/php/info.php
    permissions: '0644'
    content: |
      <?php
      phpinfo();
      ?>
  - path: /home/ubuntu/php/db.php
    permissions: '0644'
    content: |
      <?php
        //database
        $servername = "kn04a-db";
        $username = "root";
        $password = "tbzPass123";
        $dbname = "mysql";

        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
        }

        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result);
      ?>
  - path: /home/ubuntu/docker-compose.yml
    permissions: '0644'
    content: |
      name: kn04a

      services:
        web:
          container_name: kn04a-web
          build:
            context: /home/ubuntu
            dockerfile: .docker/web.Dockerfile
          restart: always
          ports:
            - 80:80
          depends_on:
            - db
          networks:
            - backbone
        db:
          container_name: kn04a-db
          image: mariadb:latest
          environment:
            - MARIADB_ROOT_PASSWORD=tbzPass123
          ports:
            - 3306:3306
          networks:
            - backbone
          volumes:
            - db_data:/var/lib/mysql

      networks:
        backbone:
          driver: bridge
          ipam:
            config:
              - subnet: 172.10.0.0/16
                ip_range: 172.10.5.0/24
                gateway: 172.10.5.254

      volumes:
        db_data:
          driver: local


runcmd:
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - sudo docker compose -f /home/ubuntu/docker-compose.yml up -d
