### GET: Index page
GET http://localhost:9000

### POST: Valid Sign in
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
  "email": "user@localhost.com",
  "password": "P@ssw0rd!14"
}

### POST: Invalid email Sign in
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
  "email": "user2@localhost.com",
  "password": "P@ssw0rd!14"
}

### POST: Invalid password Sign in
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
  "email": "user@localhost.com",
  "password": "123456"
}

### POST: Valid Sign up
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@localhost.com",
  "password": "P@ssw0rd!14",
  "confirmPassword": "P@ssw0rd!14"
}

### POST: Invalid email Sign up
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
  "username": "useree",
  "email": "user@",
  "password": "P@ssw0rd!14",
  "confirmPassword": "P@ssw0rd!14"
}

### POST: Invalid password Sign up
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
  "username": "userewewe",
  "email": "2323@localhost.com",
  "password": "P@",
  "confirmPassword": "P@"
}

### GET: User by ID
@id = c2d567ce-10bc-4356-ac89-be22e42ecc5a
GET http://localhost:9000/users/{{id}}