@id = 8c48c6e5-94c2-4011-b487-630c1ea428d8

### Index
GET http://localhost:9000

#### Seed (Only once) (Succeeded)
#GET http://localhost:9000/seed
#
#### SignIn as User (Succeeded
#POST http://localhost:9000/auth/signin
#Content-Type: application/json
#
#{
#  "email": "user@localhost.com",
#  "password": "user123"
#}
#
#> {%
#    client.global.set("auth_token", response.body.accessToken);
#%}
#
#### SignIn as Moderator
#POST http://localhost:9000/auth/signin
#Content-Type: application/json
#
#{
#  "email": "moderator@localhost.com",
#  "password": "moderator123"
#}
#
#> {%
#    client.global.set("auth_token", response.body.accessToken);
#%}

### SignIn as Admin
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
  "email": "admin@localhost.com",
  "password": "admin123"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

#### Get all roles
#GET http://localhost:9000/roles
#Authorization: Bearer {{auth_token}}
#
### SignUp
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@localhost.com",
  "password": "test1234"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

#### SignIn
#POST http://localhost:9000/auth/signin
#Content-Type: application/json
#
#{
#  "email": "test2@localhost.com",
#  "password": "test1234"
#}
#
#> {%
#    client.global.set("auth_token", response.body.accessToken);
#%}
#
#### Find user by Id
#GET http://localhost:9000/users/{{id}}
#Authorization: Bearer {{auth_token}}
#
#### Get all users
#GET http://localhost:9000/users
#Authorization: Bearer {{auth_token}}

#### PATCH user
#PATCH http://localhost:9000/users/{{id}}
#Content-Type: application/json
#Authorization: Bearer {{auth_token}}
#
#{
#  "email": "tested@localhost.com"
#}

#### Delete user by Id
#DELETE http://localhost:9000/users/{{id}}
#Authorization: Bearer {{auth_token}}