#cloud-config
# https://www.techrepublic.com/article/how-to-install-neo4j-ubuntu-server/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPIIO8uY8oWIihDv0tCAbX6toyG1RYkaLZyfGD1L+I07K4CnwAVBSU+81vw3Yv5sN9tj2Ccve9kzEeCNMld2mDP/Tt7edkx2MCToVfVx+njqwY/XbMY9bfdRKJLhIoLavuVNLnnkSIXdtlGr3JF71hPHzBDMEo64ofPCQ8hPsGxL1u3efb12jcWcRhudKtv7Qh6cVE47Zj4xImfi6VlLqwzcKZ5oCqR/z1hLLL+/pS3eM5Qsor5wmAqNfH4+z5eE+pOkFm7a0Nkygv9jwXIqtJzFGKYDe6ciBD04pEovdvY0FTyiv2vksQOVgjtu2faG2Iv1HOG0JktCIwJ49OEgjT teacher-key
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCuWX/W66sjjNiDNuPpKgYO1xFqDoMJoeo5hz2LDNrF teacher-key-wir
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5J5spKO9mDVPnH1RQEhf09XqmoFLqrHUURRZiG3qn+R0eRPfB9D6m4Y7CK6MhKj+TZzp5vCMOI6OMYRNz3LH25J9SQ/cEY6KVf/R4dd5eELRGuFCEGV+zhdu49bC6bLe5oYHBT9855Np+Q+T5GEGa9lM/PGWhll4HTY4IF+oG1TUlXvbLTPCQlVn/HHmm00MeQ0qpyFPntx939JHsM689PDtCs+Uq6AeYklLqBIpeqHtXRT0HPJGJUAY1UJE64B0pW7F/+bx2uwEuVnkGGSIWcbK+jZrj8fBjq8eflepaD4xMFlL30MkzwdpC0o3yOHOfYjLEDZW+fEur5afQBtz47p0nBO56SNQ0o/x6FK2LdzNn0cfrvRG7fHNoLRO4wL9eTwfXEDt5A43jTpS0RY45N4qWE4ap1LOM5Lrx9ZF4CUIHP94omkVwy00MCtHURpDXP8hwyFzY5w5qNt1uKxPEyuteTe+XE6pDG4tPNvFIZKrMPc6chbyPwjTsfN3+l2bGM2P7roXP30uD7PmqIZJHTytUffkHv6HmNmD4HZo+8DWnjfknsTotiN0JHRjcuEJVW4bgpA9iW1YFQqpvbem1rHHi137AJTT8EjvcGbrZfP1IjHRqEO/cx6vVKPgxWi9sUYVtZm4fpYTUEQSaSkPdzyjigYJs5gyH0FiiU7ZX3Q== sxnic@sxnic
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - unzip
  - gnupg
  - curl
runcmd:
  - curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
  - echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update -y
  - sudo apt install neo4j -y
  - sudo systemctl enable neo4j.service
  - sudo systemctl start neo4j.service
  - sudo sed -i 's/#server.default_listen_address/server.default_listen_address/g' /etc/neo4j/neo4j.conf
  - sudo systemctl restart neo4j.service
# default username and password are "neo4j" (without the quotes)
